dist: xenial
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"
# Install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py build
  - python setup.py install

# Script to run
script:
  - jetburn --version
  - echo "passed"

# Github Branch
branches:
  only:
    - master
